# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp
  
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'PKHUD'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  
  pod 'JSQMessagesViewController'
  pod 'SDWebImage'
  pod 'FirebaseUI/Storage'

end










